name: Publish .NET App Binaries

on:
  push:
    tags:
      - 'v*'  

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            rid: win-x64
            ext: zip
          - os: ubuntu-latest
            rid: linux-x64
            ext: tar.gz
          - os: macos-latest
            rid: osx-x64
            ext: tar.gz

    name: Build for ${{ matrix.rid }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish App
        run: |
          dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -p:PublishSingleFile=true -o publish

      - name: Archive build
        shell: bash
        run: |
          cd publish
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            pwsh -Command "Compress-Archive -Path * -DestinationPath ../countmycode-${{ matrix.rid }}.zip"
          else
            tar -czf ../app-${{ matrix.rid }}.tar.gz *
          fi


      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: app-${{ matrix.rid }}.${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
